
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  FINANCE_STAFF: 'FINANCE_STAFF',
  MARKETPLACE_SELLER: 'MARKETPLACE_SELLER',
  REALTOR: 'REALTOR',
  CUSTOMER: 'CUSTOMER'
} as const

export type Role = keyof typeof ROLES

export const ROLE_SETS = {
  ADMIN: [ROLES.SUPER_ADMIN],
  FINANCE: [ROLES.SUPER_ADMIN, ROLES.FINANCE_STAFF],
  MARKETPLACE: [ROLES.SUPER_ADMIN, ROLES.MARKETPLACE_SELLER],
  REALESTATE: [ROLES.SUPER_ADMIN, ROLES.REALTOR]
}
